version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "7050:7050"
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "7000:7000"
    environment:
      - PORT=7000